#!/bin/bash

set -eu -o pipefail
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

function task_deploy {
  ncftpput -R -v -u ${FTP_USER:-$(pass 'pelle.io/ftp/userid')} -p ${FTP_PASSWORD:-$(pass 'pelle.io/ftp/password')} ftp.pelle.io / ${DIR}/public/*
}

function task_build {
  docker run -it --rm -v $(pwd):/hugo solidnerd/hugo
}

function task_usage {
  echo "Usage: $0 build | deploy"
  exit 1
}

CMD=${1:-}
shift || true
case ${CMD} in
  build) task_build ;;
  deploy) task_deploy ;;
  *) task_usage ;;
esac
